# Generated by Django 4.2.30 on 2026-04-19 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empleado', models.CharField(max_length=20, unique=True, verbose_name='Código de Empleado')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('tipo_sangre', models.CharField(blank=True, max_length=3, verbose_name='Tipo de Sangre')),
                ('nombre_contacto_emergencia', models.CharField(blank=True, max_length=100, verbose_name='Contacto de Emergencia')),
                ('telefono_contacto_emergencia', models.CharField(blank=True, max_length=20, verbose_name='Teléfono Contacto')),
                ('notas_medicas', models.TextField(blank=True, verbose_name='Notas Médicas')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
            },
        ),
    ]
