# Generated by Django 4.2.30 on 2026-04-19 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_generico', models.CharField(max_length=100, unique=True, verbose_name='Nombre Genérico')),
                ('nombre_comercial', models.CharField(blank=True, max_length=100, verbose_name='Nombre Comercial')),
                ('formula_quimica', models.TextField(blank=True, verbose_name='Fórmula Química')),
                ('laboratorio', models.CharField(blank=True, max_length=100, verbose_name='Laboratorio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nombre_generico'],
            },
        ),
        migrations.CreateModel(
            name='RegistroMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(verbose_name='Fecha del Registro')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('tratamiento', models.TextField(blank=True, verbose_name='Tratamiento Prescrito')),
                ('enfermera', models.CharField(blank=True, max_length=100, verbose_name='Enfermera Atendiente')),
                ('datos_custom', models.JSONField(default=dict, verbose_name='Datos Personalizados')),
                ('seguimiento_requerido', models.BooleanField(default=False, verbose_name='¿Requiere Seguimiento?')),
                ('fecha_seguimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Seguimiento')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_medicos', to='usuarios.usuario', verbose_name='Médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.personal', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Registro Médico',
                'verbose_name_plural': 'Registros Médicos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='RecetaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=50, verbose_name='Dosis Indicada')),
                ('frecuencia', models.CharField(max_length=50, verbose_name='Frecuencia de Toma')),
                ('duracion', models.CharField(max_length=50, verbose_name='Duración del Tratamiento')),
                ('notas', models.TextField(blank=True, verbose_name='Notas Adicionales')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.medicamento', verbose_name='Medicamento')),
                ('registro_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='farmacia.registromedico', verbose_name='Registro Médico')),
            ],
            options={
                'verbose_name': 'Receta de Medicamento',
                'verbose_name_plural': 'Recetas de Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='InventarioFarmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_stock', models.IntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('nivel_minimo', models.IntegerField(default=5, verbose_name='Nivel Mínimo de Alerta')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('proveedor', models.CharField(blank=True, max_length=100, verbose_name='Proveedor')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('medicamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='farmacia.medicamento', verbose_name='Medicamento')),
            ],
            options={
                'verbose_name': 'Inventario Farmacia',
                'verbose_name_plural': 'Inventarios Farmacia',
                'ordering': ['medicamento__nombre_generico'],
            },
        ),
        migrations.CreateModel(
            name='DispensacionMedicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad Entregada')),
                ('fecha_dispensa', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Dispensa')),
                ('notas', models.TextField(blank=True, verbose_name='Notas Adicionales')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('administrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensaciones', to='usuarios.usuario', verbose_name='Administrado por')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farmacia.medicamento', verbose_name='Medicamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.personal', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Dispensación de Medicamentos',
                'verbose_name_plural': 'Dispensaciones de Medicamentos',
                'ordering': ['-fecha_dispensa'],
            },
        ),
    ]
