# Generated by Django 4.2.30 on 2026-04-19 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensacionmedicamentos',
            name='creado_el',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='dispensacionmedicamentos',
            name='fecha_dispensa',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Dispensa'),
        ),
        migrations.AlterField(
            model_name='inventariofarmacia',
            name='creado_el',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='creado_el',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='recetamedicamento',
            name='creado_el',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='registromedico',
            name='creado_el',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado el'),
        ),
    ]
