# Generated by Django 4.2.30 on 2026-04-19 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_alter_dispensacionmedicamentos_creado_el_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariofarmacia',
            name='actualizado_el',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='registromedico',
            name='actualizado_el',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Actualizado el'),
        ),
    ]
