# Generated by Django 4.2.30 on 2026-04-19 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_alter_role_creado_el'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='actualizado_el',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última actualización'),
        ),
    ]
