# Generated by Django 4.2.30 on 2026-04-19 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0003_alter_personal_actualizado_el'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('heart_attack', 'Infarto'), ('accident', 'Accidente'), ('stroke', 'Accidente Cerebrovascular'), ('allergic_reaction', 'Reacción Alérgica'), ('respiratory', 'Problema Respiratorio'), ('other', 'Otro')], max_length=50, verbose_name='Tipo de Alerta')),
                ('descripcion', models.TextField(verbose_name='Descripción del Evento')),
                ('estado', models.CharField(choices=[('active', 'Activo'), ('resolved', 'Resuelto'), ('ignored', 'Ignorado')], default='active', max_length=20, verbose_name='Estado')),
                ('equipo_responsable', models.JSONField(blank=True, null=True, verbose_name='Equipo Responsable')),
                ('hora_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Respuesta')),
                ('resuelto_el', models.DateTimeField(blank=True, null=True, verbose_name='Resuelto el')),
                ('creado_el', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado el')),
                ('actualizado_el', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Actualizado el')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.personal', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Emergencia',
                'verbose_name_plural': 'Emergencias',
                'ordering': ['-creado_el'],
            },
        ),
    ]
