# Generated by Django 4.2.30 on 2026-04-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_actualizado_el'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default='default', max_length=128, verbose_name='Contraseña'),
        ),
    ]
