# Generated by Django 4.2.30 on 2026-04-19 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0003_alter_personal_actualizado_el'),
        ('usuarios', '0003_alter_usuario_actualizado_el'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateTimeField(verbose_name='Fecha y Hora de la Cita')),
                ('estado', models.CharField(choices=[('scheduled', 'Programada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='scheduled', max_length=20, verbose_name='Estado')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo de la Consulta')),
                ('notas', models.TextField(blank=True, verbose_name='Notas Adicionales')),
                ('creado_el', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado el')),
                ('actualizado_el', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Actualizado el')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_atendidas', to='usuarios.usuario', verbose_name='Doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.personal', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha_cita'],
            },
        ),
    ]
